<a href="https://colab.research.google.com/github/Elwing-Chou/tibame20260804/blob/main/tibame20260825.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import json
import urllib.request as req
import pandas as pd
import os

# 如果資料夾不存在, 就創造資料夾
def download_danmu(sn):
    dirname = "baha/鬼滅"
    if not os.path.exists(dirname):
        os.makedirs(dirname)

    # sn = "38250"
    url = f"https://api.gamer.com.tw/anime/v1/danmu.php?videoSn={sn}&geo=TW%2CHK"
    f = req.urlopen(url)
    content = f.read()
    content = json.loads(content)

    danmus = content["data"]["danmu"]

    df = pd.DataFrame(danmus)
    df.to_csv(f"{dirname}/{sn}.csv", encoding="utf-8", index=False)
    return df

download_danmu("38331")

,text,color,size,position,time,sn,userid
0,我先來簽啦～,#FF0026,2,1,0,39631385,kellymich
1,簽🌭️,#FDE53D,1,0,0,40334844,shackle9487
2,簽,#B538FA,1,1,0,40716593,kuaxin487
3,簽,#FFFFFF,1,0,0,45882962,s206179
4,qian,#FF02D3,2,0,0,46135316,tch123
...,...,...,...,...,...,...,...
2996,好看,#FFFFFF,1,0,14250,39602691,sh6122198
2997,義勇親自用自己的呼吸法下字XDDD,#FF9496,2,2,14250,39632170,kellymich
2998,義勇笑了,#00C3FC,2,2,14250,41057738,st841513
2999,2025.7.29 *,#FFFFFF,1,0,14250,45903298,s935602
3000,好可愛,#FFFFFF,1,0,14250,46134147,xuniannian35

In [2]:
# demo 字串
a = 8
b = 24
s1 = str(a) + "/" + str(b)
s1 = "{}/{}".format(a, b)
s1 = f"{a}/{b}"
print(s1)

8/24

- 定義功能
    - 參數: 先用符號替代
    - 回傳值: return

In [3]:
def add(a, b):
    c = a + b
    return c

print(add(3, 5))
print(add(4, 6))
print(add(5, 7))

8
10
12

- HTTP代碼
    - 2: 成功
    - 3: 轉址
    - 4: 錯誤
        - 404: Not Found
            - 通常都是你網址打錯
        - 403: Forbidden
            - ip 被 ban
                - 後面幾次才被拒絕
                - 最好不要送網址送太快
                - 如果真的被 ban -> 等/換ip
            - Headers不夠完整
                - 最常被檢查的是user-agent

- 問題和回復
    - 網址+額外訊息(request headers) !!! 控制
    - 回復+額外訊息(response headers)

In [4]:
import urllib.request as req
# BeautifulSoup4
import bs4 as bs

# url = "https://ani.gamer.com.tw/animeVideo.php?sn=38250"
url = "https://github.com/Elwing-Chou/tibame20260804/raw/refs/heads/main/baha.html"
h = {
    "User-Agent":"Mozilla/5.0"
}
r = req.Request(url, headers=h)
resp = req.urlopen(r)
content = resp.read()
# bytes->list/dict: json.loads
html = bs.BeautifulSoup(content)
# 區塊.find 區塊.find_all (html名稱)
for link in html.find_all("a"):
    # 萃取:
    # 內容: .get_text()
    # 屬性: ["href"]
    link_href = link["href"]
    if link_href.startswith("?sn="):
        print("下載:", link_href)
        sn = link_href.replace("?sn=", "")
        print("序號:", sn)
        download_danmu(sn)

下載: ?sn=38250
序號: 38250
下載: ?sn=38331
序號: 38331
下載: ?sn=38483
序號: 38483
下載: ?sn=38484
序號: 38484
下載: ?sn=38541
序號: 38541
下載: ?sn=38606
序號: 38606
下載: ?sn=38684
序號: 38684
下載: ?sn=38750
序號: 38750
下載: ?sn=41294
序號: 41294
下載: ?sn=41295
序號: 41295
下載: ?sn=41296
序號: 41296
下載: ?sn=41297
序號: 41297
下載: ?sn=41298
序號: 41298
下載: ?sn=41299
序號: 41299
下載: ?sn=41300
序號: 41300
下載: ?sn=41301
序號: 41301

- 原始碼(html格式)
    

```
HTML格式: 由無數個長方形區塊所構成
<a href="網址"> -> 區塊開始
    顯示文字
</a> -> 區塊結束

1. 名字: 區塊到底是什麼
a: 超連結 img: 圖片 video: 影片

2. 屬性: 區塊細節
a href="網址"
img/video src="網址"

3. 顯示文字

```

In [5]:
# 字串的常用的幾個專屬功能
# google "python string method": 參考 W3School
# 專屬功能(s.replace): method
# 普通功能(print): function
# replace/split/join/strip
a = "hello" * 5
print(a)
b = a.replace("hello", ":)", 3)
print(a)
print(b)

a = "2024/08/24"
a_list = a.split("/")

b = "-".join(a_list)
print(b)

a = "              a b c       "
print(a)
# lstrip rstrip: 左右
a = a.strip()
print(a)

hellohellohellohellohello
hellohellohellohellohello
:):):)hellohello
2024-08-24
              a b c
a b c

In [6]:
# 如果你想下載
!zip -r /content/file.zip /content/baha

  adding: content/baha/ (stored 0%)
  adding: content/baha/鬼滅/ (stored 0%)
  adding: content/baha/鬼滅/41298.csv (deflated 57%)
  adding: content/baha/鬼滅/41297.csv (deflated 53%)
  adding: content/baha/鬼滅/38483.csv (deflated 55%)
  adding: content/baha/鬼滅/41299.csv (deflated 52%)
  adding: content/baha/鬼滅/38606.csv (deflated 56%)
  adding: content/baha/鬼滅/38684.csv (deflated 55%)
  adding: content/baha/鬼滅/38541.csv (deflated 56%)
  adding: content/baha/鬼滅/38750.csv (deflated 57%)
  adding: content/baha/鬼滅/41296.csv (deflated 50%)
  adding: content/baha/鬼滅/41300.csv (deflated 52%)
  adding: content/baha/鬼滅/38250.csv (deflated 55%)
  adding: content/baha/鬼滅/41295.csv (deflated 52%)
  adding: content/baha/鬼滅/38331.csv (deflated 56%)
  adding: content/baha/鬼滅/41294.csv (deflated 58%)
  adding: content/baha/鬼滅/38484.csv (deflated 57%)
  adding: content/baha/鬼滅/41301.csv (deflated 54%)

- 專屬功能
    - 字串專屬功能:
        - replace/split/join/strip
        - 從舊的東西變出一個新的回傳值(不會改變舊的)
    - list專屬功能(特別):
        - 更新概念:
            - 以前: 有些功能沒有回傳值
            - 改成: 每個功能都有回傳值, 只是有些功能回傳了 None 這個值
        - 更新概念2:
            - 以前: 沒有做=, 值就不會改變
            - 改成: 有些特殊時候, 確實會直接改(符合直覺)
        - 都直接修改, 回傳 None
        - 正確寫法: 不要設定回去!!!!!!!!!!!!
        - 如果你的紅字是 NoneType is not ..., 你就要想到是不是類似list的專屬功能!!!

In [5]:
l = [20, 30, 40]
b = l.append(99)
print(l)
print(b)

# 錯誤1
print(l.append(300))
# 致命錯誤2
# l = l.append(999)
# print(l[0])

# 正確: 不要設定回去
l.append(777)
print(l)

[20, 30, 40, 99]
None
None
[20, 30, 40, 99, 300, 777]

In [9]:
import glob
import pandas as pd

total = []
for fp in glob.glob("baha/*/*.csv"):
    df = pd.read_csv(fp, encoding="utf-8")
    total.append(df)

total_df = pd.concat(total)
# total_df = total_df.reset_index(drop=True)
total_df

           text    color  size  position   time        sn        userid
0             簽  #A7FE39     1         0      0  43264335      k9219059
1           簽個頭  #00C3FC     1         0     15  45656616    ye20140122
2    蛇柱：下一關你死定了  #FFFFFF     1         0     51  49402187  baseball2470
3    蛇柱：活的不耐煩了？  #FFFFFF     1         0    159  47133648  baseball2470
4        姐弟組好美好  #FFFFFF     1         0    175  46099535   ivy20110515
..          ...      ...   ...       ...    ...       ...           ...
360         QAQ  #FFFFFF     1         0  24188  46056235    double5915
361  希望死掉是一場戲QQ  #FFFFFF     1         0  24192  44614828    huejen1225
362     大哥!!!!!  #FFFFFF     1         0  24192  46809258    a123042003
363       大哥顯靈了  #FFFFFF     1         0  24199  49773941  S0983simpoke
364       大哥><!  #FFFFFF     1         0  24210  49636063    sophia2266

[25462 rows x 7 columns]